// <auto-generated />
using System;
using MaintenanceWorkflow.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MaintenanceWorkflow.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260417103203_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MaintenanceWorkflow.Api.Domain.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CurativeWorkflowId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CurativeWorkflowId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("MaintenanceWorkflow.Api.Domain.Entities.NonConformity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentStatusId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("WorkflowId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CurrentStatusId");

                    b.HasIndex("WorkflowId");

                    b.ToTable("NonConformities");
                });

            modelBuilder.Entity("MaintenanceWorkflow.Api.Domain.Entities.StatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("DateUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("FromStatusId")
                        .HasColumnType("int");

                    b.Property<int>("NonConformityId")
                        .HasColumnType("int");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RoleUsed")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("ToStatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FromStatusId");

                    b.HasIndex("NonConformityId");

                    b.HasIndex("ToStatusId");

                    b.ToTable("StatusHistories");
                });

            modelBuilder.Entity("MaintenanceWorkflow.Api.Domain.Entities.Workflow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Workflows");
                });

            modelBuilder.Entity("MaintenanceWorkflow.Api.Domain.Entities.WorkflowStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFinal")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInitial")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("WorkflowId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId");

                    b.ToTable("WorkflowStatuses");
                });

            modelBuilder.Entity("MaintenanceWorkflow.Api.Domain.Entities.WorkflowTransition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("FromStatusId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RoleAllowed")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("ToStatusId")
                        .HasColumnType("int");

                    b.Property<int>("WorkflowId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FromStatusId");

                    b.HasIndex("ToStatusId");

                    b.HasIndex("WorkflowId", "FromStatusId", "ActionName", "RoleAllowed")
                        .IsUnique();

                    b.ToTable("WorkflowTransitions");
                });

            modelBuilder.Entity("MaintenanceWorkflow.Api.Domain.Entities.Company", b =>
                {
                    b.HasOne("MaintenanceWorkflow.Api.Domain.Entities.Workflow", "CurativeWorkflow")
                        .WithMany()
                        .HasForeignKey("CurativeWorkflowId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CurativeWorkflow");
                });

            modelBuilder.Entity("MaintenanceWorkflow.Api.Domain.Entities.NonConformity", b =>
                {
                    b.HasOne("MaintenanceWorkflow.Api.Domain.Entities.Company", "Company")
                        .WithMany("NonConformities")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MaintenanceWorkflow.Api.Domain.Entities.WorkflowStatus", "CurrentStatus")
                        .WithMany()
                        .HasForeignKey("CurrentStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MaintenanceWorkflow.Api.Domain.Entities.Workflow", "Workflow")
                        .WithMany()
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("CurrentStatus");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("MaintenanceWorkflow.Api.Domain.Entities.StatusHistory", b =>
                {
                    b.HasOne("MaintenanceWorkflow.Api.Domain.Entities.WorkflowStatus", "FromStatus")
                        .WithMany()
                        .HasForeignKey("FromStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MaintenanceWorkflow.Api.Domain.Entities.NonConformity", "NonConformity")
                        .WithMany("History")
                        .HasForeignKey("NonConformityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MaintenanceWorkflow.Api.Domain.Entities.WorkflowStatus", "ToStatus")
                        .WithMany()
                        .HasForeignKey("ToStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromStatus");

                    b.Navigation("NonConformity");

                    b.Navigation("ToStatus");
                });

            modelBuilder.Entity("MaintenanceWorkflow.Api.Domain.Entities.WorkflowStatus", b =>
                {
                    b.HasOne("MaintenanceWorkflow.Api.Domain.Entities.Workflow", "Workflow")
                        .WithMany("Statuses")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("MaintenanceWorkflow.Api.Domain.Entities.WorkflowTransition", b =>
                {
                    b.HasOne("MaintenanceWorkflow.Api.Domain.Entities.WorkflowStatus", "FromStatus")
                        .WithMany("FromTransitions")
                        .HasForeignKey("FromStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MaintenanceWorkflow.Api.Domain.Entities.WorkflowStatus", "ToStatus")
                        .WithMany("ToTransitions")
                        .HasForeignKey("ToStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MaintenanceWorkflow.Api.Domain.Entities.Workflow", "Workflow")
                        .WithMany("Transitions")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromStatus");

                    b.Navigation("ToStatus");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("MaintenanceWorkflow.Api.Domain.Entities.Company", b =>
                {
                    b.Navigation("NonConformities");
                });

            modelBuilder.Entity("MaintenanceWorkflow.Api.Domain.Entities.NonConformity", b =>
                {
                    b.Navigation("History");
                });

            modelBuilder.Entity("MaintenanceWorkflow.Api.Domain.Entities.Workflow", b =>
                {
                    b.Navigation("Statuses");

                    b.Navigation("Transitions");
                });

            modelBuilder.Entity("MaintenanceWorkflow.Api.Domain.Entities.WorkflowStatus", b =>
                {
                    b.Navigation("FromTransitions");

                    b.Navigation("ToTransitions");
                });
#pragma warning restore 612, 618
        }
    }
}
